### ISSUE TITLE
Direct panel/variable editor URLs in the output of "find"

### ISSUE THREAD

**Issue by oplehto** [panodata/grafana-wtf#43]
This is an excellent tool! Thank you!

It would be really handy to have the direct URL to the panel or variable editor in the `find` output. 

This would make the panel fixing workflow a lot smoother:
1. Review all the queries for a given data source type in bulk
2. Spot a bad query
3. Hop on to the editor to fix it just by clicking the link

**Comment by amotl** [comment]
Hi Olli-Pekka,

thanks, appreciate you are finding this tool useful.

> It would be really handy to have the direct URL to the panel or variable editor in the find output.

If it's missing there, it should certainly be added. Ah, let me emphasize: You are referring to the **direct** URL to

- the panel, i.e. adding the `editPanel=N` query parameter correspondingly?
- the variable editor, i.e. adding the `editview=templating`  query parameter correspondingly?

Otherwise, can you provide corresponding examples of _direct URLs_ you would like to see?

With kind regards,
Andreas.

**Comment by oplehto** [comment]
Yes, exactly: `editPanel` and `editview` URLs.  

I just realized that the template queries do not really have a direct URL but just the `editview=templating` is good enough at least for me.

**Comment by amotl** [comment]
Thank you for clarifying. It will probably take some time for me to get back to another iteration on `grafana-wtf` [^1]. When doing so, it will probably be an easy update.

[^1]: In the meanwhile, everyone from the community is encouraged to submit patches.

**Comment by amotl** [comment]
Hi again,

GH-56 brings in a corresponding patch, which implements this feature.

With kind regards,
Andreas.

**Comment by amotl** [comment]
I've just released grafana-wtf 0.14.0, which includes the corresponding improvement. Let me know if that works for you.

**Comment by amotl** [comment]
Hi again,

I think it will be safe to close this issue. Please do not hesitate to re-open if you think the new feature could be improved further. Thank you very much for suggesting this feature.

With kind regards,
Andreas.
